-- Migration: Initial Data Setup
-- Version: v3_initial_data
-- Description: Insert initial data into the database

-- =====================================================
-- 1. INSERT DEFAULT DATA
-- =====================================================

-- Insert default economic activities (Colombian economic activities)
INSERT INTO economic_activities (name,code) VALUES ('Cultivo de cereales (excepto arroz), legumbres y semillas oleaginosas ','111');
INSERT INTO economic_activities (name,code) VALUES ('Cultivo de arroz ','112');
INSERT INTO economic_activities (name,code) VALUES ('Cultivo de hortalizas, raíces y tubérculos ','113');
INSERT INTO economic_activities (name,code) VALUES ('Cultivo de tabaco ','114');
INSERT INTO economic_activities (name,code) VALUES ('Cultivo de plantas textiles ','115');
INSERT INTO economic_activities (name,code) VALUES ('Otros cultivos transitorios n.c.p.','119');
INSERT INTO economic_activities (name,code) VALUES ('Cultivo de frutas tropicales y subtropicales','121');
INSERT INTO economic_activities (name,code) VALUES ('Cultivo de plátano y banano','122');
INSERT INTO economic_activities (name,code) VALUES ('Cultivo de café','123');
INSERT INTO economic_activities (name,code) VALUES ('Cultivo de caña de azúcar','124');
INSERT INTO economic_activities (name,code) VALUES ('Cultivo de flor de corte','125');
INSERT INTO economic_activities (name,code) VALUES ('Cultivo de palma para aceite (palma africana) y otros frutos oleaginosos','126');
INSERT INTO economic_activities (name,code) VALUES ('Cultivo de plantas con las que se preparan bebidas','127');
INSERT INTO economic_activities (name,code) VALUES ('Cultivo de especias y de plantas aromáticas y medicinales ','128');
INSERT INTO economic_activities (name,code) VALUES ('Otros cultivos permanentes n.c.p.','129');
INSERT INTO economic_activities (name,code) VALUES ('Propagación de plantas (actividades de los viveros, excepto viveros forestales) ','130');
INSERT INTO economic_activities (name,code) VALUES ('Cría de ganado bovino y bufalino','141');
INSERT INTO economic_activities (name,code) VALUES ('Cría de caballos y otros equinos ','142');
INSERT INTO economic_activities (name,code) VALUES ('Cría de ovejas y cabras ','143');
INSERT INTO economic_activities (name,code) VALUES ('Cría de ganado porcino','144');
INSERT INTO economic_activities (name,code) VALUES ('Cría de aves de corral','145');
INSERT INTO economic_activities (name,code) VALUES ('Cría de otros animales n.c.p.','149');
INSERT INTO economic_activities (name,code) VALUES ('Explotación mixta (agrícola y pecuaria) ','150');
INSERT INTO economic_activities (name,code) VALUES ('Actividades de apoyo a la agricultura ','161');
INSERT INTO economic_activities (name,code) VALUES ('Actividades de apoyo a la ganadería','162');
INSERT INTO economic_activities (name,code) VALUES ('Actividades posteriores a la cosecha ','163');
INSERT INTO economic_activities (name,code) VALUES ('Tratamiento de semillas para propagación ','164');
INSERT INTO economic_activities (name,code) VALUES ('Caza ordinaria y mediante trampas y actividades de servicios conexas ','170');
INSERT INTO economic_activities (name,code) VALUES ('Silvicultura y otras actividades forestales','210');
INSERT INTO economic_activities (name,code) VALUES ('Extracción de madera ','220');
INSERT INTO economic_activities (name,code) VALUES ('Recolección de productos forestales diferentes a la madera','230');
INSERT INTO economic_activities (name,code) VALUES ('Servicios de apoyo a la silvicultura ','240');
INSERT INTO economic_activities (name,code) VALUES ('Pesca marítima ','311');
INSERT INTO economic_activities (name,code) VALUES ('Pesca de agua dulce ','312');
INSERT INTO economic_activities (name,code) VALUES ('Acuicultura marítima ','321');
INSERT INTO economic_activities (name,code) VALUES ('Acuicultura de agua dulce','322');
INSERT INTO economic_activities (name,code) VALUES ('Extracción de hulla (carbón de piedra)','510');
INSERT INTO economic_activities (name,code) VALUES ('Extracción de carbón lignito.','520');
INSERT INTO economic_activities (name,code) VALUES ('Extracción de petróleo crudo','610');
INSERT INTO economic_activities (name,code) VALUES ('Extracción de gas natural','620');
INSERT INTO economic_activities (name,code) VALUES ('Extracción de minerales de hierro','710');
INSERT INTO economic_activities (name,code) VALUES ('Extracción de minerales de uranio y de torio','721');
INSERT INTO economic_activities (name,code) VALUES ('Extracción de oro y otros metales preciosos','722');
INSERT INTO economic_activities (name,code) VALUES ('Extracción de minerales de níquel','723');
INSERT INTO economic_activities (name,code) VALUES ('Extracción de otros minerales metalíferos no ferrosos n.c.p.','729');
INSERT INTO economic_activities (name,code) VALUES ('Extracción de piedra, arena, arcillas comunes, yeso y anhidrita','811');
INSERT INTO economic_activities (name,code) VALUES ('Extracción de arcillas de uso industrial, caliza, caolín y bentonitas','812');
INSERT INTO economic_activities (name,code) VALUES ('Extracción de esmeraldas, piedras preciosas y semipreciosas','820');
INSERT INTO economic_activities (name,code) VALUES ('Extracción de minerales para la fabricación de abonos y productos químicos','891');
INSERT INTO economic_activities (name,code) VALUES ('Extracción de halita (sal)','892');
INSERT INTO economic_activities (name,code) VALUES ('Extracción de otros minerales no metálicos n.c.p.','899');
INSERT INTO economic_activities (name,code) VALUES ('Actividades de apoyo para la extracción de petróleo y de gas natural','910');
INSERT INTO economic_activities (name,code) VALUES ('Actividades de apoyo para otras actividades de explotación de minas y canteras','990');
INSERT INTO economic_activities (name,code) VALUES ('Procesamiento y conservación de carne y productos cárnicos','1011');
INSERT INTO economic_activities (name,code) VALUES ('Procesamiento y conservación de pescados, crustáceos y moluscos','1012');
INSERT INTO economic_activities (name,code) VALUES ('Procesamiento y conservación de frutas, legumbres, hortalizas y tubérculos','1020');
INSERT INTO economic_activities (name,code) VALUES ('Elaboración de aceites y grasas de origen vegetal y animal','1030');
INSERT INTO economic_activities (name,code) VALUES ('Elaboración de productos lácteos','1040');
INSERT INTO economic_activities (name,code) VALUES ('Elaboración de productos de molinería','1051');
INSERT INTO economic_activities (name,code) VALUES ('Elaboración de almidones y productos derivados del almidón','1052');
INSERT INTO economic_activities (name,code) VALUES ('Trilla de café','1061');
INSERT INTO economic_activities (name,code) VALUES ('Descafeinado, tostión y molienda del café','1062');
INSERT INTO economic_activities (name,code) VALUES ('Otros derivados del café','1063');
INSERT INTO economic_activities (name,code) VALUES ('Elaboración y refinación de azúcar','1071');
INSERT INTO economic_activities (name,code) VALUES ('Elaboración de panela','1072');
INSERT INTO economic_activities (name,code) VALUES ('Elaboración de productos de panadería','1081');
INSERT INTO economic_activities (name,code) VALUES ('Elaboración de cacao, chocolate y productos de confitería','1082');
INSERT INTO economic_activities (name,code) VALUES ('Elaboración de macarrones, fideos, alcuzcuz y productos farináceos similares','1083');
INSERT INTO economic_activities (name,code) VALUES ('Elaboración de comidas y platos preparados','1084');
INSERT INTO economic_activities (name,code) VALUES ('Elaboración de otros productos alimenticios n.c.p.','1089');
INSERT INTO economic_activities (name,code) VALUES ('Elaboración de alimentos preparados para animales','1090');
INSERT INTO economic_activities (name,code) VALUES ('Destilación, rectificación y mezcla de bebidas alcohólicas','1101');
INSERT INTO economic_activities (name,code) VALUES ('Elaboración de bebidas fermentadas no destiladas','1102');
INSERT INTO economic_activities (name,code) VALUES ('Producción de malta, elaboración de cervezas y otras bebidas malteadas','1103');
INSERT INTO economic_activities (name,code) VALUES ('Elaboración de bebidas no alcohólicas, producción de aguas minerales y de otras aguas embotelladas','1104');
INSERT INTO economic_activities (name,code) VALUES ('Elaboración de productos de tabaco','1200');
INSERT INTO economic_activities (name,code) VALUES ('Preparación e hilatura de fibras textiles','1311');
INSERT INTO economic_activities (name,code) VALUES ('Tejeduría de productos textiles','1312');
INSERT INTO economic_activities (name,code) VALUES ('Acabado de productos textiles','1313');
INSERT INTO economic_activities (name,code) VALUES ('Fabricación de tejidos de punto y ganchillo','1391');
INSERT INTO economic_activities (name,code) VALUES ('Confección de artículos con materiales textiles, excepto prendas de vestir','1392');
INSERT INTO economic_activities (name,code) VALUES ('Fabricación de tapetes y alfombras para pisos','1393');
INSERT INTO economic_activities (name,code) VALUES ('Fabricación de cuerdas, cordeles, cables, bramantes y redes','1394');
INSERT INTO economic_activities (name,code) VALUES ('Fabricación de otros artículos textiles n.c.p.','1399');
INSERT INTO economic_activities (name,code) VALUES ('Confección de prendas de vestir, excepto prendas de piel','1410');
INSERT INTO economic_activities (name,code) VALUES ('Fabricación de artículos de piel','1420');
INSERT INTO economic_activities (name,code) VALUES ('Fabricación de artículos de punto y ganchillo','1430');
INSERT INTO economic_activities (name,code) VALUES ('Curtido y recurtido de cueros; recurtido y teñido de pieles','1511');
INSERT INTO economic_activities (name,code) VALUES ('Fabricación de artículos de viaje, bolsos de mano y artículos similares elaborados en cuero, y fabricación de artículos de talabartería y guarnicionería','1512');
INSERT INTO economic_activities (name,code) VALUES ('Fabricación de artículos de viaje, bolsos de mano y artículos similares; artículos de talabartería y guarnicionería elaborados en otros materiales','1513');
INSERT INTO economic_activities (name,code) VALUES ('Fabricación de calzado de cuero y piel, con cualquier tipo de suela','1521');
INSERT INTO economic_activities (name,code) VALUES ('Fabricación de otros tipos de calzado, excepto calzado de cuero y piel','1522');
INSERT INTO economic_activities (name,code) VALUES ('Fabricación de partes del calzado','1523');
INSERT INTO economic_activities (name,code) VALUES ('Aserrado, acepillado e impregnación de la madera','1610');
INSERT INTO economic_activities (name,code) VALUES ('Fabricación de hojas de madera para enchapado; fabricación de tableros contrachapados, tableros laminados, tableros de partículas y otros tableros y paneles','1620');
INSERT INTO economic_activities (name,code) VALUES ('Fabricación de partes y piezas de madera, de carpintería y ebanistería para la construcción','1630');
INSERT INTO economic_activities (name,code) VALUES ('Fabricación de recipientes de madera','1640');
INSERT INTO economic_activities (name,code) VALUES ('Fabricación de otros productos de madera; fabricación de artículos de corcho, cestería y espartería','1690');
INSERT INTO economic_activities (name,code) VALUES ('Fabricación de pulpas (pastas) celulósicas; papel y cartón','1701');
INSERT INTO economic_activities (name,code) VALUES ('Fabricación de papel y cartón ondulado (corrugado); fabricación de envases, empaques y de embalajes de papel y cartón.','1702');
INSERT INTO economic_activities (name,code) VALUES ('Fabricación de otros artículos de papel y cartón','1709');
INSERT INTO economic_activities (name,code) VALUES ('Actividades de impresión','1811');
INSERT INTO economic_activities (name,code) VALUES ('Actividades de servicios relacionados con la impresión','1812');
INSERT INTO economic_activities (name,code) VALUES ('Producción de copias a partir de grabaciones originales ','1820');
INSERT INTO economic_activities (name,code) VALUES ('Fabricación de productos de hornos de coque','1910');
INSERT INTO economic_activities (name,code) VALUES ('Fabricación de productos de la refinación del petróleo','1921');
INSERT INTO economic_activities (name,code) VALUES ('Actividad de mezcla de combustibles','1922');
INSERT INTO economic_activities (name,code) VALUES ('Fabricación de sustancias y productos químicos básicos','2011');
INSERT INTO economic_activities (name,code) VALUES ('Fabricación de abonos y compuestos inorgánicos nitrogenados','2012');
INSERT INTO economic_activities (name,code) VALUES ('Fabricación de plásticos en formas primarias','2013');
INSERT INTO economic_activities (name,code) VALUES ('Fabricación de caucho sintético en formas primarias','2014');
INSERT INTO economic_activities (name,code) VALUES ('Fabricación de plaguicidas y otros productos químicos de uso agropecuario','2021');
INSERT INTO economic_activities (name,code) VALUES ('Fabricación de pinturas, barnices y revestimientos similares, tintas para impresión y masillas','2022');
INSERT INTO economic_activities (name,code) VALUES ('Fabricación de jabones y detergentes, preparados para limpiar y pulir; perfumes y preparados de tocador','2023');
INSERT INTO economic_activities (name,code) VALUES ('Fabricación de otros productos químicos n.c.p.','2029');
INSERT INTO economic_activities (name,code) VALUES ('Fabricación de fibras sintéticas y artificiales','2030');
INSERT INTO economic_activities (name,code) VALUES ('Fabricación de productos farmacéuticos, sustancias químicas medicinales y productos botánicos de uso farmacéutico','2100');
INSERT INTO economic_activities (name,code) VALUES ('Fabricación de llantas y neumáticos de caucho','2211');
INSERT INTO economic_activities (name,code) VALUES ('Reencauche de llantas usadas','2212');
INSERT INTO economic_activities (name,code) VALUES ('Fabricación de formas básicas de caucho y otros productos de caucho n.c.p.','2219');
INSERT INTO economic_activities (name,code) VALUES ('Fabricación de formas básicas de plástico','2221');
INSERT INTO economic_activities (name,code) VALUES ('Fabricación de artículos de plástico n.c.p.','2229');
INSERT INTO economic_activities (name,code) VALUES ('Fabricación de vidrio y productos de vidrio','2310');
INSERT INTO economic_activities (name,code) VALUES ('Fabricación de productos refractarios','2391');
INSERT INTO economic_activities (name,code) VALUES ('Fabricación de materiales de arcilla para la construcción','2392');
INSERT INTO economic_activities (name,code) VALUES ('Fabricación de otros productos de cerámica y porcelana','2393');
INSERT INTO economic_activities (name,code) VALUES ('Fabricación de cemento, cal y yeso','2394');
INSERT INTO economic_activities (name,code) VALUES ('Fabricación de artículos de hormigón, cemento y yeso','2395');
INSERT INTO economic_activities (name,code) VALUES ('Corte, tallado y acabado de la piedra','2396');
INSERT INTO economic_activities (name,code) VALUES ('Fabricación de otros productos minerales no metálicos n.c.p.','2399');
INSERT INTO economic_activities (name,code) VALUES ('Industrias básicas de hierro y de acero','2410');
INSERT INTO economic_activities (name,code) VALUES ('Industrias básicas de metales preciosos','2421');
INSERT INTO economic_activities (name,code) VALUES ('Industrias básicas de otros metales no ferrosos','2429');
INSERT INTO economic_activities (name,code) VALUES ('Fundición de hierro y de acero','2431');
INSERT INTO economic_activities (name,code) VALUES ('Fundición de metales no ferrosos ','2432');
INSERT INTO economic_activities (name,code) VALUES ('Fabricación de productos metálicos para uso estructural','2511');
INSERT INTO economic_activities (name,code) VALUES ('Fabricación de tanques, depósitos y recipientes de metal, excepto los utilizados para el envase o transporte de mercancías','2512');
INSERT INTO economic_activities (name,code) VALUES ('Fabricación de generadores de vapor, excepto calderas de agua caliente para calefacción central','2513');
INSERT INTO economic_activities (name,code) VALUES ('Fabricación de armas y municiones','2520');
INSERT INTO economic_activities (name,code) VALUES ('Forja, prensado, estampado y laminado de metal; pulvimetalurgia','2591');
INSERT INTO economic_activities (name,code) VALUES ('Tratamiento y revestimiento de metales; mecanizado','2592');
INSERT INTO economic_activities (name,code) VALUES ('Fabricación de artículos de cuchillería, herramientas de mano y artículos de ferretería','2593');
INSERT INTO economic_activities (name,code) VALUES ('Fabricación de otros productos elaborados de metal n.c.p.','2599');
INSERT INTO economic_activities (name,code) VALUES ('Fabricación de componentes y tableros electrónicos','2610');
INSERT INTO economic_activities (name,code) VALUES ('Fabricación de computadoras y de equipo periférico','2620');
INSERT INTO economic_activities (name,code) VALUES ('Fabricación de equipos de comunicación','2630');
INSERT INTO economic_activities (name,code) VALUES ('Fabricación de aparatos electrónicos de consumo','2640');
INSERT INTO economic_activities (name,code) VALUES ('Fabricación de equipo de medición, prueba, navegación y control','2651');
INSERT INTO economic_activities (name,code) VALUES ('Fabricación de relojes','2652');
INSERT INTO economic_activities (name,code) VALUES ('Fabricación de equipo de irradiación y equipo electrónico de uso médico y terapéutico','2660');
INSERT INTO economic_activities (name,code) VALUES ('Fabricación de instrumentos ópticos y equipo fotográfico','2670');
INSERT INTO economic_activities (name,code) VALUES ('Fabricación de medios magnéticos y ópticos para almacenamiento de datos','2680');
INSERT INTO economic_activities (name,code) VALUES ('Fabricación de motores, generadores y transformadores eléctricos','2711');
INSERT INTO economic_activities (name,code) VALUES ('Fabricación de aparatos de distribución y control de la energía eléctrica','2712');
INSERT INTO economic_activities (name,code) VALUES ('Fabricación de pilas, baterías y acumuladores eléctricos','2720');
INSERT INTO economic_activities (name,code) VALUES ('Fabricación de hilos y cables eléctricos y de fibra óptica','2731');
INSERT INTO economic_activities (name,code) VALUES ('Fabricación de dispositivos de cableado','2732');
INSERT INTO economic_activities (name,code) VALUES ('Fabricación de equipos eléctricos de iluminación','2740');
INSERT INTO economic_activities (name,code) VALUES ('Fabricación de aparatos de uso doméstico','2750');
INSERT INTO economic_activities (name,code) VALUES ('Fabricación de otros tipos de equipo eléctrico n.c.p.','2790');
INSERT INTO economic_activities (name,code) VALUES ('Fabricación de motores, turbinas, y partes para motores de combustión interna','2811');
INSERT INTO economic_activities (name,code) VALUES ('Fabricación de equipos de potencia hidráulica y neumática','2812');
INSERT INTO economic_activities (name,code) VALUES ('Fabricación de otras bombas, compresores, grifos y válvulas','2813');
INSERT INTO economic_activities (name,code) VALUES ('Fabricación de cojinetes, engranajes, trenes de engranajes y piezas de transmisión','2814');
INSERT INTO economic_activities (name,code) VALUES ('Fabricación de hornos, hogares y quemadores industriales','2815');
INSERT INTO economic_activities (name,code) VALUES ('Fabricación de equipo de elevación y manipulación','2816');
INSERT INTO economic_activities (name,code) VALUES ('Fabricación de maquinaria y equipo de oficina (excepto computadoras y equipo periférico)','2817');
INSERT INTO economic_activities (name,code) VALUES ('Fabricación de herramientas manuales con motor','2818');
INSERT INTO economic_activities (name,code) VALUES ('Fabricación de otros tipos de maquinaria y equipo de uso general n.c.p.','2819');
INSERT INTO economic_activities (name,code) VALUES ('Fabricación de maquinaria agropecuaria y forestal','2821');
INSERT INTO economic_activities (name,code) VALUES ('Fabricación de máquinas formadoras de metal y de máquinas herramienta','2822');
INSERT INTO economic_activities (name,code) VALUES ('Fabricación de maquinaria para la metalurgia','2823');
INSERT INTO economic_activities (name,code) VALUES ('Fabricación de maquinaria para explotación de minas y canteras y para obras de construcción','2824');
INSERT INTO economic_activities (name,code) VALUES ('Fabricación de maquinaria para la elaboración de alimentos, bebidas y tabaco','2825');
INSERT INTO economic_activities (name,code) VALUES ('Fabricación de maquinaria para la elaboración de productos textiles, prendas de vestir y cueros','2826');
INSERT INTO economic_activities (name,code) VALUES ('Fabricación de otros tipos de maquinaria y equipo de uso especial n.c.p.','2829');
INSERT INTO economic_activities (name,code) VALUES ('Fabricación de vehículos automotores y sus motores','2910');
INSERT INTO economic_activities (name,code) VALUES ('Fabricación de carrocerías para vehículos automotores; fabricación de remolques y semirremolques ','2920');
INSERT INTO economic_activities (name,code) VALUES ('Fabricación de partes, piezas (autopartes) y accesorios (lujos) para vehículos automotores','2930');
INSERT INTO economic_activities (name,code) VALUES ('Construcción de barcos y de estructuras flotantes','3011');
INSERT INTO economic_activities (name,code) VALUES ('Construcción de embarcaciones de recreo y deporte','3012');
INSERT INTO economic_activities (name,code) VALUES ('Fabricación de locomotoras y de material rodante para ferrocarriles','3020');
INSERT INTO economic_activities (name,code) VALUES ('Fabricación de aeronaves, naves espaciales y de maquinaria conexa','3030');
INSERT INTO economic_activities (name,code) VALUES ('Fabricación de motocicletas','3091');
INSERT INTO economic_activities (name,code) VALUES ('Fabricación de bicicletas y de sillas de ruedas para personas con discapacidad','3092');
INSERT INTO economic_activities (name,code) VALUES ('Fabricación de otros tipos de equipo de transporte n.c.p.','3099');
INSERT INTO economic_activities (name,code) VALUES ('Fabricación de muebles ','3110');
INSERT INTO economic_activities (name,code) VALUES ('Fabricación de colchones y somieres','3120');
INSERT INTO economic_activities (name,code) VALUES ('Fabricación de joyas, bisutería y artículos conexos','3210');
INSERT INTO economic_activities (name,code) VALUES ('Fabricación de instrumentos musicales','3220');
INSERT INTO economic_activities (name,code) VALUES ('Fabricación de artículos y equipo para la práctica del deporte','3230');
INSERT INTO economic_activities (name,code) VALUES ('Fabricación de juegos, juguetes y rompecabezas','3240');
INSERT INTO economic_activities (name,code) VALUES ('Fabricación de instrumentos, aparatos y materiales médicos y odontológicos (incluido mobiliario)','3250');
INSERT INTO economic_activities (name,code) VALUES ('Otras industrias manufactureras n.c.p.','3290');
INSERT INTO economic_activities (name,code) VALUES ('Mantenimiento y reparación especializado de productos elaborados en metal','3311');
INSERT INTO economic_activities (name,code) VALUES ('Mantenimiento y reparación especializado de maquinaria y equipo','3312');
INSERT INTO economic_activities (name,code) VALUES ('Mantenimiento y reparación especializado de equipo electrónico y óptico','3313');
INSERT INTO economic_activities (name,code) VALUES ('Mantenimiento y reparación especializado de equipo eléctrico','3314');
INSERT INTO economic_activities (name,code) VALUES ('Mantenimiento y reparación especializado de equipo de transporte, excepto los vehículos automotores, motocicletas y bicicletas','3315');
INSERT INTO economic_activities (name,code) VALUES ('Mantenimiento y reparación de otros tipos de equipos y sus componentes n.c.p.','3319');
INSERT INTO economic_activities (name,code) VALUES ('Instalación especializada de maquinaria y equipo industrial ','3320');
INSERT INTO economic_activities (name,code) VALUES ('Generación de energía eléctrica','3511');
INSERT INTO economic_activities (name,code) VALUES ('Transmisión de energía eléctrica','3512');
INSERT INTO economic_activities (name,code) VALUES ('Distribución de energía eléctrica','3513');
INSERT INTO economic_activities (name,code) VALUES ('Comercialización de energía eléctrica','3514');
INSERT INTO economic_activities (name,code) VALUES ('Producción de gas; distribución de combustibles gaseosos por tuberías','3520');
INSERT INTO economic_activities (name,code) VALUES ('Suministro de vapor y aire acondicionado','3530');
INSERT INTO economic_activities (name,code) VALUES ('Captación, tratamiento y distribución de agua','3600');
INSERT INTO economic_activities (name,code) VALUES ('Evacuación y tratamiento de aguas residuales','3700');
INSERT INTO economic_activities (name,code) VALUES ('Recolección de desechos no peligrosos','3811');
INSERT INTO economic_activities (name,code) VALUES ('Recolección de desechos peligrosos','3812');
INSERT INTO economic_activities (name,code) VALUES ('Tratamiento y disposición de desechos no peligrosos','3821');
INSERT INTO economic_activities (name,code) VALUES ('Tratamiento y disposición de desechos peligrosos','3822');
INSERT INTO economic_activities (name,code) VALUES ('Recuperación de materiales','3830');
INSERT INTO economic_activities (name,code) VALUES ('Actividades de saneamiento ambiental y otros servicios de gestión de desechos','3900');
INSERT INTO economic_activities (name,code) VALUES ('Construcción de edificios residenciales','4111');
INSERT INTO economic_activities (name,code) VALUES ('Construcción de edificios no residenciales','4112');
INSERT INTO economic_activities (name,code) VALUES ('Construcción de carreteras y vías de ferrocarril','4210');
INSERT INTO economic_activities (name,code) VALUES ('Construcción de proyectos de servicio público','4220');
INSERT INTO economic_activities (name,code) VALUES ('Construcción de otras obras de ingeniería civil','4290');
INSERT INTO economic_activities (name,code) VALUES ('Demolición','4311');
INSERT INTO economic_activities (name,code) VALUES ('Preparación del terreno','4312');
INSERT INTO economic_activities (name,code) VALUES ('Instalaciones eléctricas','4321');
INSERT INTO economic_activities (name,code) VALUES ('Instalaciones de fontanería, calefacción y aire acondicionado','4322');
INSERT INTO economic_activities (name,code) VALUES ('Otras instalaciones especializadas','4329');
INSERT INTO economic_activities (name,code) VALUES ('Terminación y acabado de edificios y obras de ingeniería civil','4330');
INSERT INTO economic_activities (name,code) VALUES ('Otras actividades especializadas para la construcción de edificios y obras de ingeniería civil','4390');
INSERT INTO economic_activities (name,code) VALUES ('Comercio de vehículos automotores nuevos','4511');
INSERT INTO economic_activities (name,code) VALUES ('Comercio de vehículos automotores usados','4512');
INSERT INTO economic_activities (name,code) VALUES ('Mantenimiento y reparación de vehículos automotores','4520');
INSERT INTO economic_activities (name,code) VALUES ('Comercio de partes, piezas (autopartes) y accesorios (lujos) para vehículos automotores','4530');
INSERT INTO economic_activities (name,code) VALUES ('Comercio de motocicletas y de sus partes, piezas y accesorios','4541');
INSERT INTO economic_activities (name,code) VALUES ('Mantenimiento y reparación de motocicletas y de sus partes y piezas','4542');
INSERT INTO economic_activities (name,code) VALUES ('Comercio al por mayor a cambio de una retribución o por contrata','4610');
INSERT INTO economic_activities (name,code) VALUES ('Comercio al por mayor de materias primas agropecuarias; animales vivos','4620');
INSERT INTO economic_activities (name,code) VALUES ('Comercio al por mayor de productos alimenticios','4631');
INSERT INTO economic_activities (name,code) VALUES ('Comercio al por mayor de bebidas y tabaco','4632');
INSERT INTO economic_activities (name,code) VALUES ('Comercio al por mayor de productos textiles, productos confeccionados para uso doméstico','4641');
INSERT INTO economic_activities (name,code) VALUES ('Comercio al por mayor de prendas de vestir','4642');
INSERT INTO economic_activities (name,code) VALUES ('Comercio al por mayor de calzado','4643');
INSERT INTO economic_activities (name,code) VALUES ('Comercio al por mayor de aparatos y equipo de uso doméstico','4644');
INSERT INTO economic_activities (name,code) VALUES ('Comercio al por mayor de productos farmacéuticos, medicinales, cosméticos y de tocador','4645');
INSERT INTO economic_activities (name,code) VALUES ('Comercio al por mayor de otros utensilios domésticos n.c.p.','4649');
INSERT INTO economic_activities (name,code) VALUES ('Comercio al por mayor de computadores, equipo periférico y programas de informática','4651');
INSERT INTO economic_activities (name,code) VALUES ('Comercio al por mayor de equipo, partes y piezas electrónicos y de telecomunicaciones','4652');
INSERT INTO economic_activities (name,code) VALUES ('Comercio al por mayor de maquinaria y equipo agropecuarios','4653');
INSERT INTO economic_activities (name,code) VALUES ('Comercio al por mayor de otros tipos de maquinaria y equipo n.c.p.','4659');
INSERT INTO economic_activities (name,code) VALUES ('Comercio al por mayor de combustibles sólidos, líquidos, gaseosos y productos conexos','4661');
INSERT INTO economic_activities (name,code) VALUES ('Comercio al por mayor de metales y productos metalíferos','4662');
INSERT INTO economic_activities (name,code) VALUES ('Comercio al por mayor de materiales de construcción, artículos de ferretería, pinturas, productos de vidrio, equipo y materiales de fontanería y calefacción','4663');
INSERT INTO economic_activities (name,code) VALUES ('Comercio al por mayor de productos químicos básicos, cauchos y plásticos en formas primarias y productos químicos de uso agropecuario','4664');
INSERT INTO economic_activities (name,code) VALUES ('Comercio al por mayor de desperdicios, desechos y chatarra','4665');
INSERT INTO economic_activities (name,code) VALUES ('Comercio al por mayor de otros productos n.c.p.','4669');
INSERT INTO economic_activities (name,code) VALUES ('Comercio al por mayor no especializado','4690');
INSERT INTO economic_activities (name,code) VALUES ('Comercio al por menor en establecimientos no especializados con surtido compuesto principalmente por alimentos, bebidas (alcohólicas y no alcohólicas) o tabaco','4711');
INSERT INTO economic_activities (name,code) VALUES ('Comercio al por menor en establecimientos no especializados, con surtido compuesto principalmente por productos diferentes de alimentos (víveres en general), bebidas (alcohólicas y no alcohólicas) y tabaco','4719');
INSERT INTO economic_activities (name,code) VALUES ('Comercio al por menor de productos agrícolas para el consumo en establecimientos especializados','4721');
INSERT INTO economic_activities (name,code) VALUES ('Comercio al por menor de leche, productos lácteos y huevos, en establecimientos especializados','4722');
INSERT INTO economic_activities (name,code) VALUES ('Comercio al por menor de carnes (incluye aves de corral), productos cárnicos, pescados y productos de mar, en establecimientos especializados','4723');
INSERT INTO economic_activities (name,code) VALUES ('Comercio al por menor de bebidas y productos del tabaco, en establecimientos especializados','4724');
INSERT INTO economic_activities (name,code) VALUES ('Comercio al por menor de otros productos alimenticios n.c.p., en establecimientos especializados','4729');
INSERT INTO economic_activities (name,code) VALUES ('Comercio al por menor de combustible para automotores','4731');
INSERT INTO economic_activities (name,code) VALUES ('Comercio al por menor de lubricantes (aceites, grasas), aditivos y productos de limpieza para vehículos automotores','4732');
INSERT INTO economic_activities (name,code) VALUES ('Comercio al por menor de computadores, equipos periféricos, programas de informática y equipos de telecomunicaciones en establecimientos especializados','4741');
INSERT INTO economic_activities (name,code) VALUES ('Comercio al por menor de equipos y aparatos de sonido y de video, en establecimientos especializados','4742');
INSERT INTO economic_activities (name,code) VALUES ('Comercio al por menor de productos textiles en establecimientos especializados','4751');
INSERT INTO economic_activities (name,code) VALUES ('Comercio al por menor de artículos de ferretería, pinturas y productos de vidrio en establecimientos especializados','4752');
INSERT INTO economic_activities (name,code) VALUES ('Comercio al por menor de tapices, alfombras y recubrimientos para paredes y pisos en establecimientos especializados','4753');
INSERT INTO economic_activities (name,code) VALUES ('Comercio al por menor de electrodomésticos y gasodomésticos de uso doméstico, muebles y equipos de iluminación en establecimientos especializados','4754');
INSERT INTO economic_activities (name,code) VALUES ('Comercio al por menor de artículos y utensilios de uso doméstico en establecimientos especializados','4755');
INSERT INTO economic_activities (name,code) VALUES ('Comercio al por menor de otros artículos domésticos en establecimientos especializados','4759');
INSERT INTO economic_activities (name,code) VALUES ('Comercio al por menor de libros, periódicos, materiales y artículos de papelería y escritorio, en establecimientos especializados','4761');
INSERT INTO economic_activities (name,code) VALUES ('Comercio al por menor de artículos deportivos, en establecimientos especializados ','4762');
INSERT INTO economic_activities (name,code) VALUES ('Comercio al por menor de otros artículos culturales y de entretenimiento n.c.p. en establecimientos especializados','4769');
INSERT INTO economic_activities (name,code) VALUES ('Comercio al por menor de prendas de vestir y sus accesorios (incluye artículos de piel) en establecimientos especializados','4771');
INSERT INTO economic_activities (name,code) VALUES ('Comercio al por menor de todo tipo de calzado y artículos de cuero y sucedáneos del cuero en establecimientos especializados.','4772');
INSERT INTO economic_activities (name,code) VALUES ('Comercio al por menor de productos farmacéuticos y medicinales, cosméticos y artículos de tocador en establecimientos especializados','4773');
INSERT INTO economic_activities (name,code) VALUES ('Comercio al por menor de otros productos nuevos en establecimientos especializados','4774');
INSERT INTO economic_activities (name,code) VALUES ('Comercio al por menor de artículos de segunda mano','4775');
INSERT INTO economic_activities (name,code) VALUES ('Comercio al por menor de alimentos, bebidas y tabaco, en puestos de venta móviles','4781');
INSERT INTO economic_activities (name,code) VALUES ('Comercio al por menor de productos textiles, prendas de vestir y calzado, en puestos de venta móviles','4782');
INSERT INTO economic_activities (name,code) VALUES ('Comercio al por menor de otros productos en puestos de venta móviles','4789');
INSERT INTO economic_activities (name,code) VALUES ('Comercio al por menor realizado a través de Internet','4791');
INSERT INTO economic_activities (name,code) VALUES ('Comercio al por menor realizado a través de casas de venta o por correo','4792');
INSERT INTO economic_activities (name,code) VALUES ('Otros tipos de comercio al por menor no realizado en establecimientos, puestos de venta o mercados.','4799');
INSERT INTO economic_activities (name,code) VALUES ('Transporte férreo de pasajeros','4911');
INSERT INTO economic_activities (name,code) VALUES ('Transporte férreo de carga ','4912');
INSERT INTO economic_activities (name,code) VALUES ('Transporte de pasajeros','4921');
INSERT INTO economic_activities (name,code) VALUES ('Transporte mixto','4922');
INSERT INTO economic_activities (name,code) VALUES ('Transporte de carga por carretera','4923');
INSERT INTO economic_activities (name,code) VALUES ('Transporte por tuberías','4930');
INSERT INTO economic_activities (name,code) VALUES ('Transporte de pasajeros marítimo y de cabotaje ','5011');
INSERT INTO economic_activities (name,code) VALUES ('Transporte de carga marítimo y de cabotaje ','5012');
INSERT INTO economic_activities (name,code) VALUES ('Transporte fluvial de pasajeros','5021');
INSERT INTO economic_activities (name,code) VALUES ('Transporte fluvial de carga','5022');
INSERT INTO economic_activities (name,code) VALUES ('Transporte aéreo nacional de pasajeros ','5111');
INSERT INTO economic_activities (name,code) VALUES ('Transporte aéreo internacional de pasajeros ','5112');
INSERT INTO economic_activities (name,code) VALUES ('Transporte aéreo nacional de carga ','5121');
INSERT INTO economic_activities (name,code) VALUES ('Transporte aéreo internacional de carga ','5122');
INSERT INTO economic_activities (name,code) VALUES ('Almacenamiento y depósito','5210');
INSERT INTO economic_activities (name,code) VALUES ('Actividades de estaciones, vías y servicios complementarios para el transporte terrestre','5221');
INSERT INTO economic_activities (name,code) VALUES ('Actividades de puertos y servicios complementarios para el transporte acuático','5222');
INSERT INTO economic_activities (name,code) VALUES ('Actividades de aeropuertos, servicios de navegación aérea y demás actividades conexas al transporte aéreo','5223');
INSERT INTO economic_activities (name,code) VALUES ('Manipulación de carga','5224');
INSERT INTO economic_activities (name,code) VALUES ('Otras actividades complementarias al transporte','5229');
INSERT INTO economic_activities (name,code) VALUES ('Actividades postales nacionales','5310');
INSERT INTO economic_activities (name,code) VALUES ('Actividades de mensajería','5320');
INSERT INTO economic_activities (name,code) VALUES ('Alojamiento en hoteles ','5511');
INSERT INTO economic_activities (name,code) VALUES ('Alojamiento en apartahoteles','5512');
INSERT INTO economic_activities (name,code) VALUES ('Alojamiento en centros vacacionales ','5513');
INSERT INTO economic_activities (name,code) VALUES ('Alojamiento rural','5514');
INSERT INTO economic_activities (name,code) VALUES ('Otros tipos de alojamientos para visitantes','5519');
INSERT INTO economic_activities (name,code) VALUES ('Actividades de zonas de camping y parques para vehículos recreacionales','5520');
INSERT INTO economic_activities (name,code) VALUES ('Servicio de estancia por horas ','5530');
INSERT INTO economic_activities (name,code) VALUES ('Otros tipos de alojamiento n.c.p.','5590');
INSERT INTO economic_activities (name,code) VALUES ('Expendio a la mesa de comidas preparadas','5611');
INSERT INTO economic_activities (name,code) VALUES ('Expendio por autoservicio de comidas preparadas','5612');
INSERT INTO economic_activities (name,code) VALUES ('Expendio de comidas preparadas en cafeterías','5613');
INSERT INTO economic_activities (name,code) VALUES ('Otros tipos de expendio de comidas preparadas n.c.p.','5619');
INSERT INTO economic_activities (name,code) VALUES ('Catering para eventos','5621');
INSERT INTO economic_activities (name,code) VALUES ('Actividades de otros servicios de comidas','5629');
INSERT INTO economic_activities (name,code) VALUES ('Expendio de bebidas alcohólicas para el consumo dentro del establecimiento','5630');
INSERT INTO economic_activities (name,code) VALUES ('Edición de libros','5811');
INSERT INTO economic_activities (name,code) VALUES ('Edición de directorios y listas de correo','5812');
INSERT INTO economic_activities (name,code) VALUES ('Edición de periódicos, revistas y otras publicaciones periódicas','5813');
INSERT INTO economic_activities (name,code) VALUES ('Otros trabajos de edición','5819');
INSERT INTO economic_activities (name,code) VALUES ('Edición de programas de informática (software)','5820');
INSERT INTO economic_activities (name,code) VALUES ('Actividades de producción de películas cinematográficas, videos, programas, anuncios y comerciales de televisión','5911');
INSERT INTO economic_activities (name,code) VALUES ('Actividades de posproducción de películas cinematográficas, videos, programas, anuncios y comerciales de televisión','5912');
INSERT INTO economic_activities (name,code) VALUES ('Actividades de distribución de películas cinematográficas, videos, programas, anuncios y comerciales de televisión','5913');
INSERT INTO economic_activities (name,code) VALUES ('Actividades de exhibición de películas cinematográficas y videos','5914');
INSERT INTO economic_activities (name,code) VALUES ('Actividades de grabación de sonido y edición de musica','5920');
INSERT INTO economic_activities (name,code) VALUES ('Actividades de programación y transmisión en el servicio de radiodifusión sonora','6010');
INSERT INTO economic_activities (name,code) VALUES ('Actividades de programación y transmisión de televisión','6020');
INSERT INTO economic_activities (name,code) VALUES ('Actividades de telecomunicaciones alámbricas','6110');
INSERT INTO economic_activities (name,code) VALUES ('Actividades de telecomunicaciones inalámbricas','6120');
INSERT INTO economic_activities (name,code) VALUES ('Actividades de telecomunicación satelital','6130');
INSERT INTO economic_activities (name,code) VALUES ('Otras actividades de telecomunicaciones','6190');
INSERT INTO economic_activities (name,code) VALUES ('Actividades de desarrollo de sistemas informáticos (planificación, análisis, diseño, programación, pruebas)','6201');
INSERT INTO economic_activities (name,code) VALUES ('Actividades de consultoría informática y actividades de administración de instalaciones informáticas','6202');
INSERT INTO economic_activities (name,code) VALUES ('Otras actividades de tecnologías de información y actividades de servicios informáticos','6209');
INSERT INTO economic_activities (name,code) VALUES ('Procesamiento de datos, alojamiento (hosting) y actividades relacionadas','6311');
INSERT INTO economic_activities (name,code) VALUES ('Portales web','6312');
INSERT INTO economic_activities (name,code) VALUES ('Actividades de agencias de noticias','6391');
INSERT INTO economic_activities (name,code) VALUES ('Otras actividades de servicio de información n.c.p.','6399');
INSERT INTO economic_activities (name,code) VALUES ('Banco Central','6411');
INSERT INTO economic_activities (name,code) VALUES ('Bancos comerciales','6412');
INSERT INTO economic_activities (name,code) VALUES ('Actividades de las corporaciones financieras','6421');
INSERT INTO economic_activities (name,code) VALUES ('Actividades de las compañías de financiamiento','6422');
INSERT INTO economic_activities (name,code) VALUES ('Banca de segundo piso','6423');
INSERT INTO economic_activities (name,code) VALUES ('Actividades de las cooperativas financieras','6424');
INSERT INTO economic_activities (name,code) VALUES ('Fideicomisos, fondos y entidades financieras similares','6431');
INSERT INTO economic_activities (name,code) VALUES ('Fondos de cesantías','6432');
INSERT INTO economic_activities (name,code) VALUES ('Leasing financiero (arrendamiento financiero)','6491');
INSERT INTO economic_activities (name,code) VALUES ('Actividades financieras de fondos de empleados y otras formas asociativas del sector solidario','6492');
INSERT INTO economic_activities (name,code) VALUES ('Actividades de compra de cartera o factoring','6493');
INSERT INTO economic_activities (name,code) VALUES ('Otras actividades de distribución de fondos','6494');
INSERT INTO economic_activities (name,code) VALUES ('Instituciones especiales oficiales','6495');
INSERT INTO economic_activities (name,code) VALUES ('Capitalización','6496');
INSERT INTO economic_activities (name,code) VALUES ('Otras actividades de servicio financiero, excepto las de seguros y pensiones n.c.p.','6499');
INSERT INTO economic_activities (name,code) VALUES ('Seguros generales ','6511');
INSERT INTO economic_activities (name,code) VALUES ('Seguros de vida','6512');
INSERT INTO economic_activities (name,code) VALUES ('Reaseguros','6513');
INSERT INTO economic_activities (name,code) VALUES ('Seguros de salud','6515');
INSERT INTO economic_activities (name,code) VALUES ('Servicios de seguros sociales de salud','6521');
INSERT INTO economic_activities (name,code) VALUES ('Servicios de seguros sociales de riesgos laborales','6522');
INSERT INTO economic_activities (name,code) VALUES ('Servicios de seguros sociales en riesgos familia','6523');
INSERT INTO economic_activities (name,code) VALUES ('Régimen de prima media con prestación definida (RPM)','6531');
INSERT INTO economic_activities (name,code) VALUES ('Régimen de ahorro con solidaridad (RAIS)','6532');
INSERT INTO economic_activities (name,code) VALUES ('Administración de mercados financieros','6611');
INSERT INTO economic_activities (name,code) VALUES ('Corretaje de valores y de contratos de productos básicos','6612');
INSERT INTO economic_activities (name,code) VALUES ('Otras actividades relacionadas con el mercado de valores','6613');
INSERT INTO economic_activities (name,code) VALUES ('Actividades de las sociedades de intermediación cambiaria y de servicios financieros especiales.','6614');
INSERT INTO economic_activities (name,code) VALUES ('Actividades de los profesionales de compra y venta de divisas','6615');
INSERT INTO economic_activities (name,code) VALUES ('Otras actividades auxiliares de las actividades de servicios financieros n.c.p.','6619');
INSERT INTO economic_activities (name,code) VALUES ('Actividades de agentes y corredores de seguros','6621');
INSERT INTO economic_activities (name,code) VALUES ('Evaluación de riesgos y daños, y otras actividades de servicios auxiliares','6629');
INSERT INTO economic_activities (name,code) VALUES ('Actividades de administración de fondos','6630');
INSERT INTO economic_activities (name,code) VALUES ('Actividades inmobiliarias realizadas con bienes propios o arrendados','6810');
INSERT INTO economic_activities (name,code) VALUES ('Actividades inmobiliarias realizadas a cambio de una retribución o por contrata ','6820');
INSERT INTO economic_activities (name,code) VALUES ('Actividades jurídicas','6910');
INSERT INTO economic_activities (name,code) VALUES ('Actividades de contabilidad, teneduría de libros, auditoría financiera y asesoría tributaria','6920');
INSERT INTO economic_activities (name,code) VALUES ('Actividades de administración empresarial','7010');
INSERT INTO economic_activities (name,code) VALUES ('Actividades de consultoría de gestión','7020');
INSERT INTO economic_activities (name,code) VALUES ('Actividades de arquitectura','7111');
INSERT INTO economic_activities (name,code) VALUES ('Actividades de ingeniería y otras actividades conexas de consultoría técnica','7112');
INSERT INTO economic_activities (name,code) VALUES ('Ensayos y análisis técnicos','7120');
INSERT INTO economic_activities (name,code) VALUES ('Investigaciones y desarrollo experimental en el campo de las ciencias naturales y la ingeniería ','7210');
INSERT INTO economic_activities (name,code) VALUES ('Investigaciones y desarrollo experimental en el campo de las ciencias sociales y las humanidades','7220');
INSERT INTO economic_activities (name,code) VALUES ('Publicidad','7310');
INSERT INTO economic_activities (name,code) VALUES ('Estudios de mercado y realización de encuestas de opinión pública','7320');
INSERT INTO economic_activities (name,code) VALUES ('Actividades especializadas de diseño ','7410');
INSERT INTO economic_activities (name,code) VALUES ('Actividades de fotografía','7420');
INSERT INTO economic_activities (name,code) VALUES ('Otras actividades profesionales, científicas y técnicas n.c.p.','7490');
INSERT INTO economic_activities (name,code) VALUES ('Actividades veterinarias','7500');
INSERT INTO economic_activities (name,code) VALUES ('Alquiler y arrendamiento de vehículos automotores','7710');
INSERT INTO economic_activities (name,code) VALUES ('Alquiler y arrendamiento de equipo recreativo y deportivo','7721');
INSERT INTO economic_activities (name,code) VALUES ('Alquiler de videos y discos ','7722');
INSERT INTO economic_activities (name,code) VALUES ('Alquiler y arrendamiento de otros efectos personales y enseres domésticos n.c.p.','7729');
INSERT INTO economic_activities (name,code) VALUES ('Alquiler y arrendamiento de otros tipos de maquinaria, equipo y bienes tangibles n.c.p.','7730');
INSERT INTO economic_activities (name,code) VALUES ('Arrendamiento de propiedad intelectual y productos similares, excepto obras protegidas por derechos de autor','7740');
INSERT INTO economic_activities (name,code) VALUES ('Actividades de agencias de gestión y colocación empleo','7810');
INSERT INTO economic_activities (name,code) VALUES ('Actividades de empresas de servicios temporales','7820');
INSERT INTO economic_activities (name,code) VALUES ('Otras actividades de provisión de talento humano','7830');
INSERT INTO economic_activities (name,code) VALUES ('Actividades de las agencias de viajes','7911');
INSERT INTO economic_activities (name,code) VALUES ('Actividades de operadores turísticos','7912');
INSERT INTO economic_activities (name,code) VALUES ('Otros servicios de reserva y actividades relacionadas','7990');
INSERT INTO economic_activities (name,code) VALUES ('Actividades de seguridad privada','8010');
INSERT INTO economic_activities (name,code) VALUES ('Actividades de servicios de sistemas de seguridad','8020');
INSERT INTO economic_activities (name,code) VALUES ('Actividades de detectives e investigadores privados','8030');
INSERT INTO economic_activities (name,code) VALUES ('Actividades combinadas de apoyo a instalaciones','8110');
INSERT INTO economic_activities (name,code) VALUES ('Limpieza general interior de edificios','8121');
INSERT INTO economic_activities (name,code) VALUES ('Otras actividades de limpieza de edificios e instalaciones industriales','8129');
INSERT INTO economic_activities (name,code) VALUES ('Actividades de paisajismo y servicios de mantenimiento conexos','8130');
INSERT INTO economic_activities (name,code) VALUES ('Actividades combinadas de servicios administrativos de oficina','8211');
INSERT INTO economic_activities (name,code) VALUES ('Fotocopiado, preparación de documentos y otras actividades especializadas de apoyo a oficina','8219');
INSERT INTO economic_activities (name,code) VALUES ('Actividades de centros de llamadas (Call center)','8220');
INSERT INTO economic_activities (name,code) VALUES ('Organización de convenciones y eventos comerciales','8230');
INSERT INTO economic_activities (name,code) VALUES ('Actividades de agencias de cobranza y oficinas de calificación crediticia','8291');
INSERT INTO economic_activities (name,code) VALUES ('Actividades de envase y empaque','8292');
INSERT INTO economic_activities (name,code) VALUES ('Otras actividades de servicio de apoyo a las empresas n.c.p.','8299');
INSERT INTO economic_activities (name,code) VALUES ('Actividades legislativas de la administración pública','8411');
INSERT INTO economic_activities (name,code) VALUES ('Actividades ejecutivas de la administración pública','8412');
INSERT INTO economic_activities (name,code) VALUES ('Regulación de las actividades de organismos que prestan servicios de salud, educativos, culturales y otros servicios sociales, excepto servicios de seguridad social ','8413');
INSERT INTO economic_activities (name,code) VALUES ('Actividades reguladoras y facilitadoras de la actividad económica','8414');
INSERT INTO economic_activities (name,code) VALUES ('Actividades de los órganos de control y otras instituciones','8415');
INSERT INTO economic_activities (name,code) VALUES ('Relaciones exteriores ','8421');
INSERT INTO economic_activities (name,code) VALUES ('Actividades de defensa','8422');
INSERT INTO economic_activities (name,code) VALUES ('Orden público y actividades de seguridad','8423');
INSERT INTO economic_activities (name,code) VALUES ('Administración de justicia','8424');
INSERT INTO economic_activities (name,code) VALUES ('Actividades de planes de seguridad social de afiliación obligatoria','8430');
INSERT INTO economic_activities (name,code) VALUES ('Educación de la primera infancia','8511');
INSERT INTO economic_activities (name,code) VALUES ('Educación preescolar','8512');
INSERT INTO economic_activities (name,code) VALUES ('Educación básica primaria','8513');
INSERT INTO economic_activities (name,code) VALUES ('Educación básica secundaria ','8521');
INSERT INTO economic_activities (name,code) VALUES ('Educación media académica','8522');
INSERT INTO economic_activities (name,code) VALUES ('Educación media técnica','8523');
INSERT INTO economic_activities (name,code) VALUES ('Establecimientos que combinan diferentes niveles de educación ','8530');
INSERT INTO economic_activities (name,code) VALUES ('Educación técnica profesional','8541');
INSERT INTO economic_activities (name,code) VALUES ('Educación tecnológica','8542');
INSERT INTO economic_activities (name,code) VALUES ('Educación de instituciones universitarias o de escuelas tecnológicas','8543');
INSERT INTO economic_activities (name,code) VALUES ('Educación de universidades','8544');
INSERT INTO economic_activities (name,code) VALUES ('Formación para el trabajo','8551');
INSERT INTO economic_activities (name,code) VALUES ('Enseñanza deportiva y recreativa','8552');
INSERT INTO economic_activities (name,code) VALUES ('Enseñanza cultural','8553');
INSERT INTO economic_activities (name,code) VALUES ('Otros tipos de educación n.c.p.','8559');
INSERT INTO economic_activities (name,code) VALUES ('Actividades de apoyo a la educación','8560');
INSERT INTO economic_activities (name,code) VALUES ('Actividades de hospitales y clínicas, con internación','8610');
INSERT INTO economic_activities (name,code) VALUES ('Actividades de la práctica médica, sin internación','8621');
INSERT INTO economic_activities (name,code) VALUES ('Actividades de la práctica odontológica','8622');
INSERT INTO economic_activities (name,code) VALUES ('Actividades de apoyo diagnóstico','8691');
INSERT INTO economic_activities (name,code) VALUES ('Actividades de apoyo terapéutico','8692');
INSERT INTO economic_activities (name,code) VALUES ('Otras actividades de atención de la salud humana','8699');
INSERT INTO economic_activities (name,code) VALUES ('Actividades de atención residencial medicalizada de tipo general','8710');
INSERT INTO economic_activities (name,code) VALUES ('Actividades de atención residencial, para el cuidado de pacientes con retardo mental, enfermedad mental y consumo de sustancias psicoactivas','8720');
INSERT INTO economic_activities (name,code) VALUES ('Actividades de atención en instituciones para el cuidado de personas mayores y/o discapacitadas','8730');
INSERT INTO economic_activities (name,code) VALUES ('Otras actividades de atención en instituciones con alojamiento','8790');
INSERT INTO economic_activities (name,code) VALUES ('Actividades de asistencia social sin alojamiento para personas mayores y discapacitadas','8810');
INSERT INTO economic_activities (name,code) VALUES ('Actividades de guarderías para niños y niñas.','8891');
INSERT INTO economic_activities (name,code) VALUES ('Otras actividades de asistencia social n.c.p.','8899');
INSERT INTO economic_activities (name,code) VALUES ('Creación literaria','9001');
INSERT INTO economic_activities (name,code) VALUES ('Creación musical','9002');
INSERT INTO economic_activities (name,code) VALUES ('Creación teatral','9003');
INSERT INTO economic_activities (name,code) VALUES ('Creación audiovisual','9004');
INSERT INTO economic_activities (name,code) VALUES ('Artes plásticas y visuales','9005');
INSERT INTO economic_activities (name,code) VALUES ('Actividades teatrales','9006');
INSERT INTO economic_activities (name,code) VALUES ('Actividades de espectáculos musicales en vivo','9007');
INSERT INTO economic_activities (name,code) VALUES ('Otras actividades de espectáculos en vivo n.c.p.','9008');
INSERT INTO economic_activities (name,code) VALUES ('Actividades de bibliotecas y archivos','9101');
INSERT INTO economic_activities (name,code) VALUES ('Actividades y funcionamiento de museos, conservación de edificios y sitios históricos','9102');
INSERT INTO economic_activities (name,code) VALUES ('Actividades de jardines botánicos, zoológicos y reservas naturales','9103');
INSERT INTO economic_activities (name,code) VALUES ('Actividades de juegos de azar y apuestas','9200');
INSERT INTO economic_activities (name,code) VALUES ('Gestión de instalaciones deportivas','9311');
INSERT INTO economic_activities (name,code) VALUES ('Actividades de clubes deportivos','9312');
INSERT INTO economic_activities (name,code) VALUES ('Otras actividades deportivas','9319');
INSERT INTO economic_activities (name,code) VALUES ('Actividades de parques de atracciones y parques temáticos','9321');
INSERT INTO economic_activities (name,code) VALUES ('Otras actividades recreativas y de esparcimiento n.c.p.','9329');
INSERT INTO economic_activities (name,code) VALUES ('Actividades de asociaciones empresariales y de empleadores','9411');
INSERT INTO economic_activities (name,code) VALUES ('Actividades de asociaciones profesionales','9412');
INSERT INTO economic_activities (name,code) VALUES ('Actividades de sindicatos de empleados','9420');
INSERT INTO economic_activities (name,code) VALUES ('Actividades de asociaciones religiosas','9491');
INSERT INTO economic_activities (name,code) VALUES ('Actividades de asociaciones políticas','9492');
INSERT INTO economic_activities (name,code) VALUES ('Actividades de otras asociaciones n.c.p.','9499');
INSERT INTO economic_activities (name,code) VALUES ('Mantenimiento y reparación de computadores y de equipo periférico','9511');
INSERT INTO economic_activities (name,code) VALUES ('Mantenimiento y reparación de equipos de comunicación','9512');
INSERT INTO economic_activities (name,code) VALUES ('Mantenimiento y reparación de aparatos electrónicos de consumo','9521');
INSERT INTO economic_activities (name,code) VALUES ('Mantenimiento y reparación de aparatos y equipos domésticos y de jardinería ','9522');
INSERT INTO economic_activities (name,code) VALUES ('Reparación de calzado y artículos de cuero','9523');
INSERT INTO economic_activities (name,code) VALUES ('Reparación de muebles y accesorios para el hogar','9524');
INSERT INTO economic_activities (name,code) VALUES ('Mantenimiento y reparación de otros efectos personales y enseres domésticos','9529');
INSERT INTO economic_activities (name,code) VALUES ('Lavado y limpieza, incluso la limpieza en seco, de productos textiles y de piel','9601');
INSERT INTO economic_activities (name,code) VALUES ('Peluquería y otros tratamientos de belleza','9602');
INSERT INTO economic_activities (name,code) VALUES ('Pompas fúnebres y actividades relacionadas','9603');
INSERT INTO economic_activities (name,code) VALUES ('Otras actividades de servicios personales n.c.p.','9609');
INSERT INTO economic_activities (name,code) VALUES ('Actividades de los hogares individuales como empleadores de personal doméstico','9700');
INSERT INTO economic_activities (name,code) VALUES ('Actividades no diferenciadas de los hogares individuales como productores de bienes para uso propio','9810');
INSERT INTO economic_activities (name,code) VALUES ('Actividades no diferenciadas de los hogares individuales como productores de servicios para uso propio','9820');
INSERT INTO economic_activities (name,code) VALUES ('Actividades de organizaciones y entidades extraterritoriales','9900');

-- Insert default categories (Colombian categories)
INSERT INTO categories (name,value) VALUES ('Especial','5.50');
INSERT INTO categories (name,value) VALUES ('Primera','4.75');
INSERT INTO categories (name,value) VALUES ('Segunda','4.00');
INSERT INTO categories (name,value) VALUES ('Tercera','3.25');
INSERT INTO categories (name,value) VALUES ('Cuarta','2.50');
INSERT INTO categories (name,value) VALUES ('Quinta','1.75');
INSERT INTO categories (name,value) VALUES ('Sexta','1.00');

-- Insert default departments (Colombian departments)
INSERT INTO departments (name,code) VALUES ('ANTIOQUIA','05');
INSERT INTO departments (name,code) VALUES ('ATLANTICO','08');
INSERT INTO departments (name,code) VALUES ('BOGOTA','11');
INSERT INTO departments (name,code) VALUES ('BOLIVAR','13');
INSERT INTO departments (name,code) VALUES ('BOYACA','15');
INSERT INTO departments (name,code) VALUES ('CALDAS','17');
INSERT INTO departments (name,code) VALUES ('CAQUETA','18');
INSERT INTO departments (name,code) VALUES ('CAUCA','19');
INSERT INTO departments (name,code) VALUES ('CESAR','20');
INSERT INTO departments (name,code) VALUES ('CORDOBA','23');
INSERT INTO departments (name,code) VALUES ('CUNDINAMARCA','25');
INSERT INTO departments (name,code) VALUES ('CHOCO','27');
INSERT INTO departments (name,code) VALUES ('HUILA','41');
INSERT INTO departments (name,code) VALUES ('LA GUAJIRA','44');
INSERT INTO departments (name,code) VALUES ('MAGDALENA','47');
INSERT INTO departments (name,code) VALUES ('META','50');
INSERT INTO departments (name,code) VALUES ('NARIÑO','52');
INSERT INTO departments (name,code) VALUES ('N. DE SANTANDER','54');
INSERT INTO departments (name,code) VALUES ('QUINDIO','63');
INSERT INTO departments (name,code) VALUES ('RISARALDA','66');
INSERT INTO departments (name,code) VALUES ('SANTANDER','68');
INSERT INTO departments (name,code) VALUES ('SUCRE','70');
INSERT INTO departments (name,code) VALUES ('TOLIMA','73');
INSERT INTO departments (name,code) VALUES ('VALLE DEL CAUCA','76');
INSERT INTO departments (name,code) VALUES ('ARAUCA','81');
INSERT INTO departments (name,code) VALUES ('CASANARE','85');
INSERT INTO departments (name,code) VALUES ('PUTUMAYO','86');
INSERT INTO departments (name,code) VALUES ('SAN ANDRES','88');
INSERT INTO departments (name,code) VALUES ('AMAZONAS','91');
INSERT INTO departments (name,code) VALUES ('GUAINIA','94');
INSERT INTO departments (name,code) VALUES ('GUAVIARE','95');
INSERT INTO departments (name,code) VALUES ('VAUPES','97');
INSERT INTO departments (name,code) VALUES ('VICHADA','99');

